// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:take_your_meds/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ActiveMedsAdapter());
    registerAdapter(DosePresetAdapter());
    registerAdapter(MedsAdapter());
    registerAdapter(MedsDoseRangeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ActiveMedsAdapter());
    registerAdapter(DosePresetAdapter());
    registerAdapter(MedsAdapter());
    registerAdapter(MedsDoseRangeAdapter());
  }
}
